### ISSUE TITLE
Question about relation between TAGNet and NBFNet

### ISSUE THREAD

**Issue by Infinempty** [HarryShomer/TAGNet#1]
If I set delta to infinity and don't use Specific delta, will TAGNet become NBFNet?

**Comment by HarryShomer** [comment]
Almost! The one difference would be that while NBFNet still aggregates all empty messages we ignore most of them. In theory this shouldn't matter, as since each empty message is **0** it shouldn't make a difference if we ignore them. 

It's also worth noting that there may be small differences in our implementation that cause the results to be different than running plain NBFNet.
